name = "mongo-realm-worker"
type = "javascript"

account_id = "56f1775e3e7a2ee3090a71893cf8a1ca"
workers_dev = true                              # or zone_id = "<ZONE ID>" if you have one

main = "build/index.mjs"

[build]
command = "npm run build"
